OnlineLibrary/OnlineLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('Admin_Pages/', include('pagesForAdmin.urls')),
    path('User_Pages/', include('pagesForUser.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# انا اللي كاتب اللي تحت 
# static : conf urls static
# setting : conf

OnlineLibrary/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.Home, name='Home'),
    path('Sign_up', views.Sign_up, name='Sign_up'),
    path('Login', views.Login, name='Login'),
    path('Log_out', views.Log_out, name='Log_out'),
]

OnlineLibrary/pagesForUser/urls.py
from django.urls import path
from . import views

app_name = 'pagesForUser'

urlpatterns = [
    path('Home_user', views.Home_user, name='Home_user'),
    path('User_view_available_books', views.User_view_available_books, name='User_view_available_books'),
    path('User_view_all_books', views.User_view_all_books, name='User_view_all_books'),
    path('User_view_borrowed_books', views.User_view_borrowed_books, name='User_view_borrowed_books'),
    path('User_display_book/<str:bookId>/', views.User_display_book, name='User_display_book'),
    path('User_borrow_book/<str:bookId>/', views.User_borrow_book, name='User_borrow_book'),
    path('User_return_book/<str:bookId>/', views.User_return_book, name='User_return_book'),
    path('Search_page', views.Search_page, name='Search_page'),
]

OnlineLibrary/pagesForUser/models.py
from django.db import models

# Create your models here.

OnlineLibrary/pagesForUser/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse, JsonResponse
from pages.models import Account_admin, Account_user, Book
from django.core.files.storage import default_storage
from django.shortcuts import get_object_or_404

# Create your views here.

# Done
def Home_user(request):
    if not request.session.get('is_admin', False) and request.session.get('is_user', False):
        return render(request, 'pagesForUser/Home_user.html')
    elif request.session.get('is_admin', False) and not request.session.get('is_user', False):
        return redirect('pagesForAdmin:Home_admin')
    else:
        return redirect('pages:Home')
    
def User_view_available_books(request):
    if not request.session.get('is_admin', False) and request.session.get('is_user', False):
        books = Book.objects.all().filter(available=True)
        return render(request, 'pagesForUser/User_view_available_books.html', {'books': books})
    elif request.session.get('is_admin', False) and not request.session.get('is_user', False):
        return redirect('pagesForAdmin:Home_admin')
    else:
        return redirect('pages:Home')
    
def User_display_book(request, bookId):
    if not request.session.get('is_admin', False) and request.session.get('is_user', False):
        account = Account_user.objects.get(username=request.session.get('username'))
        book = get_object_or_404(Book, bookId=bookId)
        return render(request, 'pagesForUser/User_display_book.html', {'book': book, 'account': account})
    elif request.session.get('is_admin', False) and not request.session.get('is_user', False):
        return redirect('pagesForAdmin:Home_admin')
    else:
        return redirect('pages:Home')
    
def User_view_all_books(request):
    if not request.session.get('is_admin', False) and request.session.get('is_user', False):
        account = Account_user.objects.get(username=request.session.get('username'))
        books = Book.objects.all()
        return render(request, 'pagesForUser/User_view_all_books.html', {'books': books, 'account': account})
    elif request.session.get('is_admin', False) and not request.session.get('is_user', False):
        return redirect('pagesForAdmin:Home_admin')
    else:
        return redirect('pages:Home')
    
def User_view_borrowed_books(request):
    if not request.session.get('is_admin', False) and request.session.get('is_user', False):
        account = Account_user.objects.get(username=request.session.get('username'))
        books = Book.objects.all().filter(borrower=account, available=False)
        return render(request, 'pagesForUser/User_view_borrowed_books.html', {'books': books})
    elif request.session.get('is_admin', False) and not request.session.get('is_user', False):
        return redirect('pagesForAdmin:Home_admin')
    else:
        return redirect('pages:Home')

# not page it is function
def User_borrow_book(request, bookId):
    if not request.session.get('is_admin', False) and request.session.get('is_user', False):
        if request.method == 'POST':
            try:
                account = Account_user.objects.get(username=request.session.get('username'))
                book = Book.objects.get(bookId=bookId)
                book.available = False
                book.borrower = account
                book.save()
                return HttpResponse("Book borrowed successfully.")
            except Book.DoesNotExist:
                return JsonResponse({'error': 'Book not found'}, status=404)
        return redirect('Home_user')
    elif request.session.get('is_admin', False) and not request.session.get('is_user', False):
        return redirect('pagesForAdmin:Home_admin')
    else:
        return redirect('pages:Home')
    
# not page it is function
def User_return_book(request, bookId):
    if not request.session.get('is_admin', False) and request.session.get('is_user', False):
        if request.method == 'POST':
            try:
                book = Book.objects.get(bookId=bookId)
                book.available = True
                book.borrower = None
                book.save()
                return HttpResponse("Book returned successfully.")
            except Book.DoesNotExist:
                return JsonResponse({'error': 'Book not found'}, status=404)
        return redirect('Home_user')
    elif request.session.get('is_admin', False) and not request.session.get('is_user', False):
        return redirect('pagesForAdmin:Home_admin')
    else:
        return redirect('pages:Home')
    
def Search_page(request):
    if not request.session.get('is_admin', False) and request.session.get('is_user', False):
        if request.method == 'POST':
            account = Account_user.objects.get(username=request.session.get('username'))
            searched = request.POST['searched']
            choice = request.POST.get('Search_by', '')
            if choice == 'title':
                books = Book.objects.filter(title__contains=searched)
            elif choice == 'author':
                books = Book.objects.filter(author__contains=searched)
            elif choice == 'category':
                books = Book.objects.filter(category__contains=searched)
            else:
                books = Book.objects.filter(author__contains=searched)
            return render(request, 'pagesForUser/Search_page.html', {'searched': searched, 'choice': choice, 'books': books, 'account': account})
        else:
            return render(request, 'pagesForUser/Search_page.html', {})
    elif request.session.get('is_admin', False) and not request.session.get('is_user', False):
        return redirect('pagesForAdmin:Home_admin')
    else:
        return redirect('pages:Home')

OnlineLibrary/templates/pagesForUser/Home_user.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{% static 'Css Files/BookPages.css' %}" />
  </head>
  <body>
    <nav class="UserNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
          <li><a href="{% url 'pagesForUser:Home_user' %}">Home</a></li>
          <li class="dropdown">
                <a href="#" class="dropbtn">Books</a>
                <div class="dropdown-content">
                    <a href="{% url 'pagesForUser:User_view_all_books' %}">All books</a>
                    <a href="{% url 'pagesForUser:User_view_available_books' %}">Available books</a>
                    <a href="{% url 'pagesForUser:User_view_borrowed_books' %}">Borrowed books</a>
                </div>
          </li>
          <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
          <li>
              <form method="POST" action="{% url 'pagesForUser:Search_page' %}">
                  {% csrf_token %}
                  <input type="search" name="searched" id="bar" placeholder="Search..">
                  <select name="Search_by" id="by">
                      <option name="Author" value="author">Search by Author</option>
                      <option name="Title" value="title">Search by Title</option>
                      <option name="Category" value="category">Search by Category</option>
                  </select>
                  <button type="submit">Search</button>
              </form>
          </li>
      </ul>
    </nav>
    <div class="Home">
      <h1><b>Welcome To Library Website</b></h1>
      <p>
        This site serves as a library where you can add new books or borrow them
      </p>
    </div>
  </body>
</html>

OnlineLibrary/templates/pagesForUser/Search_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{% static 'Css Files/BookPages.css' %}" />
    <title>SearchPage</title>
</head>

<body>
    <nav class="UserNav">
        <img src="{% static 'Images/logo0.png' %}" class="logo">
        <ul>
            <li><a href="{% url 'pagesForUser:Home_user' %}">Home</a></li>
            <li class="dropdown">
                <a href="#" class="dropbtn">Books</a>
                <div class="dropdown-content">
                    <a href="{% url 'pagesForUser:User_view_all_books' %}">All books</a>
                    <a href="{% url 'pagesForUser:User_view_available_books' %}">Available books</a>
                    <a href="{% url 'pagesForUser:User_view_borrowed_books' %}">Borrowed books</a>
                </div>
            </li>
            <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
            <li>
                <form method="POST" action="{% url 'pagesForUser:Search_page' %}">
                    {% csrf_token %}
                    <input type="search" name="searched" id="bar" placeholder="Search.." value="{{ searched }}">
                    <select name="Search_by" id="by">
                        <option name="Author" value="author" {% if choice == 'author' %}selected{% endif %}>Search by Author</option>
                        <option name="Title" value="title" {% if choice == 'title' %}selected{% endif %}>Search by Title</option>
                        <option name="Category" value="category"  {% if choice == 'category' %}selected{% endif %}>Search by Category</option>
                    </select>
                    <button type="submit">Search</button>
                </form>
            </li>
        </ul>
    </nav>
    <div id="the books" class="PageContent">
        {% if searched %}
        <h1>You Searched For "{{searched}}"</h1>
        {% for book in books %}
          <div id="{{ book.bookId }}" class="book_rectangle">
            <img
              src="{{book.image.url}}"
              alt="book cover"
              width="200"
              height="300"
            />
            <div class="book_rectangle_header">
              <h3><a href="{% url 'pagesForUser:User_display_book' book.bookId %}" class="Details">{{ book.title }}</a></h3>
            </div>
            <div class="book_rectangle_body">
              <ul>
                <li><strong>Status: </strong>{% if book.available == True %}Available{% elif book.available == False %}Not Available{% endif %}</li>
                <br>
                <li><strong>Author: </strong>{{book.author}}</li>
                <br>
                <li><strong>Category: </strong>{{book.category}}</li>
                <br>
                <li>
                  <strong>Brief Description: </strong>{{book.briefDescription}}</li>
                <br>
              </ul>
            </div>
            {% if book.available == True %}
              <button onclick="borrowBook('{{book.bookId}}')"><span></span>Borrow</button>
            {% elif book.available == False and account == book.borrower %}
              <button class="returnBook" onclick="returnBook('{{book.bookId}}')"><span></span>Return Book</button>
            {% endif %}
          </div>
        {% empty %}
            <p>There is no books like your search.</p>
        {% endfor %}
        {% else %}
        <h1>You Forgot to Search :|</h1>
        {% endif %}
    </div>

    <script>const csrfToken = "{{ csrf_token }}";</script>
    <script src="{% static 'Java Script Files/Borrow.js' %}"></script>
    <script src="{% static 'Java Script Files/Return_Book.js' %}"></script>
</body>

</html>

OnlineLibrary/templates/pagesForUser/User_display_book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Available Books</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{% static 'Css Files/BookPages.css' %}" />
  </head>
  <body>
    <nav class="UserNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
          <li><a href="{% url 'pagesForUser:Home_user' %}">Home</a></li>
          <li class="dropdown">
                <a href="#" class="dropbtn">Books</a>
                <div class="dropdown-content">
                    <a href="{% url 'pagesForUser:User_view_all_books' %}">All books</a>
                    <a href="{% url 'pagesForUser:User_view_available_books' %}">Available books</a>
                    <a href="{% url 'pagesForUser:User_view_borrowed_books' %}">Borrowed books</a>
                </div>
            </li>
          <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
          <li>
              <form method="POST" action="{% url 'pagesForUser:Search_page' %}">
                  {% csrf_token %}
                  <input type="search" name="searched" id="bar" placeholder="Search..">
                  <select name="Search_by" id="by">
                      <option name="Author" value="author">Search by Author</option>
                      <option name="Title" value="title">Search by Title</option>
                      <option name="Category" value="category">Search by Category</option>
                  </select>
                  <button type="submit">Search</button>
              </form>
          </li>
      </ul>
    </nav>

    <div id="the available books" class="PageContent">
        <br /><br />
        <h1>Book Details</h1>
        
        <div id="{{ book.bookId }}" class="book_rectangle">
        <img
            src="{{book.image.url}}"
            alt="book cover"
            width="240"
            height="360"
        />
        <div class="book_rectangle_header">
            <h3>{{book.title}}</h3>
        </div>
        <div class="book_rectangle_body">
            <ul>
            <li><strong>Status: </strong>{% if book.available == True %}Available{% elif book.available == False %}Not Available{% endif %}</li>
            <br>
            <li><strong>Id: </strong>{{book.bookId}}</li>
            <br>
            <li><strong>Author: </strong>{{book.author}}</li>
            <br>
            <li><strong>Category: </strong>{{book.category}}</li>
            <br>
            <li>
                <strong>Brief Description: </strong>{{book.briefDescription}}</li>
            <br>
            <li>
                <strong>Description: </strong>{{book.description}}</li>
            </ul>
        </div>
        {% if book.available == True %}
          <button onclick="borrowBook('{{book.bookId}}')"><span></span>Borrow</button>
        {% elif book.available == False and account == book.borrower %}
          <button class="returnBook" onclick="returnBook('{{book.bookId}}')"><span></span>Return Book</button>
        {% endif %}
        </div>
    </div>

    <script>const csrfToken = "{{ csrf_token }}";</script>
    <script src="{% static 'Java Script Files/Borrow.js' %}"></script>
    <script src="{% static 'Java Script Files/Return_Book.js' %}"></script>
  </body>

</html>

OnlineLibrary/templates/pagesForUser/User_view_all_books.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>All books</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{% static 'Css Files/BookPages.css' %}" />
  </head>

  <body>
    <nav class="UserNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
          <li><a href="{% url 'pagesForUser:Home_user' %}">Home</a></li>
          <li class="dropdown">
                <a href="#" class="dropbtn">Books</a>
                <div class="dropdown-content">
                    <a href="{% url 'pagesForUser:User_view_all_books' %}">All books</a>
                    <a href="{% url 'pagesForUser:User_view_available_books' %}">Available books</a>
                    <a href="{% url 'pagesForUser:User_view_borrowed_books' %}">Borrowed books</a>
                </div>
            </li>
          <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
          <li>
              <form method="POST" action="{% url 'pagesForUser:Search_page' %}">
                  {% csrf_token %}
                  <input type="search" name="searched" id="bar" placeholder="Search..">
                  <select name="Search_by" id="by">
                      <option name="Author" value="author">Search by Author</option>
                      <option name="Title" value="title">Search by Title</option>
                      <option name="Category" value="category">Search by Category</option>
                  </select>
                  <button type="submit">Search</button>
              </form>
          </li>
      </ul>
    </nav>

    <div id="the books" class="PageContent">
        <br /><br />
        <h1>The List Of All Books</h1>
        
        {% for book in books %}
          <div id="{{ book.bookId }}" class="book_rectangle">
            <img
              src="{{book.image.url}}"
              alt="book cover"
              width="200"
              height="300"
            />
            <div class="book_rectangle_header">
              <h3><a href="{% url 'pagesForUser:User_display_book' book.bookId %}" class="Details">{{ book.title }}</a></h3>
            </div>
            <div class="book_rectangle_body">
              <ul>
                <li><strong>Status: </strong>{% if book.available == True %}Available{% elif book.available == False %}Not Available{% endif %}</li>
                <br>
                <li><strong>Author: </strong>{{book.author}}</li>
                <br>
                <li><strong>Category: </strong>{{book.category}}</li>
                <br>
                <li>
                  <strong>Brief Description: </strong>{{book.briefDescription}}</li>
                <br>
              </ul>
            </div>
            {% if book.available == True %}
              <button onclick="borrowBook('{{book.bookId}}')"><span></span>Borrow</button>
            {% elif book.available == False and account == book.borrower %}
              <button class="returnBook" onclick="returnBook('{{book.bookId}}')"><span></span>Return Book</button>
            {% endif %}
          </div>
        {% empty %}
            <p>There is no books at the moment.</p>
        {% endfor %}

    </div>

    <script>const csrfToken = "{{ csrf_token }}";</script>
    <script src="{% static 'Java Script Files/Borrow.js' %}"></script>
    <script src="{% static 'Java Script Files/Return_Book.js' %}"></script>
  </body>
</html>

OnlineLibrary/templates/pagesForUser/User_view_available_books.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Available Books</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{% static 'Css Files/BookPages.css' %}" />
  </head>
  <body>
    <nav class="UserNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
          <li><a href="{% url 'pagesForUser:Home_user' %}">Home</a></li>
          <li class="dropdown">
                <a href="#" class="dropbtn">Books</a>
                <div class="dropdown-content">
                    <a href="{% url 'pagesForUser:User_view_all_books' %}">All books</a>
                    <a href="{% url 'pagesForUser:User_view_available_books' %}">Available books</a>
                    <a href="{% url 'pagesForUser:User_view_borrowed_books' %}">Borrowed books</a>
                </div>
            </li>
          <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
          <li>
              <form method="POST" action="{% url 'pagesForUser:Search_page' %}">
                  {% csrf_token %}
                  <input type="search" name="searched" id="bar" placeholder="Search..">
                  <select name="Search_by" id="by">
                      <option name="Author" value="author">Search by Author</option>
                      <option name="Title" value="title">Search by Title</option>
                      <option name="Category" value="category">Search by Category</option>
                  </select>
                  <button type="submit">Search</button>
              </form>
          </li>
      </ul>
    </nav>
    <div id="the books" class="PageContent">
      <br /><br />
      <h1>The List Of Available Books</h1>
        
      {% for book in books %}
        {% if book.available == True %}
          <div id="{{ book.bookId }}" class="book_rectangle">
            <img
              src="{{book.image.url}}"
              alt="book cover"
              width="200"
              height="300"
            />
            <div class="book_rectangle_header">
              <h3><a href="{% url 'pagesForUser:User_display_book' book.bookId %}" class="Details">{{ book.title }}</a></h3>
            </div>
            <div class="book_rectangle_body">
              <ul>
                <li><strong>Status: </strong>{% if book.available == True %}Available{% elif book.available == False %}Not Available{% endif %}</li>
                <br>
                <li><strong>Author: </strong>{{book.author}}</li>
                <br>
                <li><strong>Category: </strong>{{book.category}}</li>
                <br>
                <li>
                  <strong>Brief Description: </strong>{{book.briefDescription}}
                </li>
                <br>
              </ul>
            </div>
            <button onclick="borrowBook('{{book.bookId}}')"><span></span>Borrow</button>
          </div>
        {% endif %}
      {% empty %}
          <p>There is no available books at the moment.</p>
      {% endfor %}

    </div>

    <script>const csrfToken = "{{ csrf_token }}";</script>
    <script src="{% static 'Java Script Files/Borrow.js' %}"></script>
  </body>

</html>

OnlineLibrary/templates/pagesForUser/User_view_borrowed_books.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Borrowed Books</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{% static 'Css Files/BookPages.css' %}" />
  </head>
  <body>
    <nav class="UserNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
          <li><a href="{% url 'pagesForUser:Home_user' %}">Home</a></li>
          <li class="dropdown">
                <a href="#" class="dropbtn">Books</a>
                <div class="dropdown-content">
                    <a href="{% url 'pagesForUser:User_view_all_books' %}">All books</a>
                    <a href="{% url 'pagesForUser:User_view_available_books' %}">Available books</a>
                    <a href="{% url 'pagesForUser:User_view_borrowed_books' %}">Borrowed books</a>
                </div>
            </li>
          <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
          <li>
              <form method="POST" action="{% url 'pagesForUser:Search_page' %}">
                  {% csrf_token %}
                  <input type="search" name="searched" id="bar" placeholder="Search..">
                  <select name="Search_by" id="by">
                      <option name="Author" value="author">Search by Author</option>
                      <option name="Title" value="title">Search by Title</option>
                      <option name="Category" value="category">Search by Category</option>
                  </select>
                  <button type="submit">Search</button>
              </form>
          </li>
      </ul>
    </nav>
    <div id="the books" class="PageContent">
      <br /><br />
      <h1>The List Of Borrowed Books</h1>
      {% for book in books %}
        {% if book.available == False %}
          <div id="{{ book.bookId }}" class="book_rectangle">
            <img
              src="{{book.image.url}}"
              alt="book cover"
              width="200"
              height="300"
            />
            <div class="book_rectangle_header">
              <h3><a href="{% url 'pagesForUser:User_display_book' book.bookId %}" class="Details">{{ book.title }}</a></h3>
            </div>
            <div class="book_rectangle_body">
              <ul>
                <li><strong>Status: </strong>{% if book.available == True %}Available{% elif book.available == False %}Not Available{% endif %}</li>
                <br>
                <li><strong>Author: </strong>{{book.author}}</li>
                <br>
                <li><strong>Category: </strong>{{book.category}}</li>
                <br>
                <li>
                  <strong>Brief Description: </strong>{{book.briefDescription}}
                </li>
                <br>
              </ul>
            </div>
            <button class="returnBook" onclick="returnBook('{{book.bookId}}')"><span></span>Return Book</button>
          </div>
        {% endif %}
      {% empty %}
          <p>There is no borrowed books at the moment.</p>
      {% endfor %}

    </div>

    <script>const csrfToken = "{{ csrf_token }}";</script>
    <script src="{% static 'Java Script Files/Return_Book.js' %}"></script>
  </body>

</html>