OnlineLibrary/OnlineLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('Admin_Pages/', include('pagesForAdmin.urls')),
    path('User_Pages/', include('pagesForUser.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# انا اللي كاتب اللي تحت 
# static : conf urls static
# setting : conf

OnlineLibrary/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.Home, name='Home'),
    path('Sign_up', views.Sign_up, name='Sign_up'),
    path('Login', views.Login, name='Login'),
    path('Log_out', views.Log_out, name='Log_out'),
]

OnlineLibrary/pagesForAdmin/urls.py
from django.urls import path
from . import views

app_name = 'pagesForAdmin'

urlpatterns = [
    path('Home_admin', views.Home_admin, name='Home_admin'),
    path('Add_book', views.Add_book, name='Add_book'),
    path('Edit_book/<str:bookId>/', views.Edit_book, name='Edit_book'),
    path('Admin_view_available_books', views.Admin_view_available_books, name='Admin_view_available_books'),
    path('Admin_view_all_books', views.Admin_view_all_books, name='Admin_view_all_books'),
    path('Admin_display_book/<str:bookId>/', views.Admin_display_book, name='Admin_display_book'),
    path('Admin_delete_book/<str:bookId>/', views.Admin_delete_book, name='Admin_delete_book'),
]

OnlineLibrary/pagesForAdmin/models.py
from django.db import models

# Create your models here.

OnlineLibrary/pagesForAdmin/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse, JsonResponse
from pages.models import Account_admin, Account_user, Book
from django.core.files.storage import default_storage
from django.shortcuts import get_object_or_404

# Create your views here.

# Done    
def Home_admin(request):
    # print(request.session.get('username'))
    if request.session.get('is_admin', False) and not request.session.get('is_user', False):
        return render(request, 'pagesForAdmin\Home_Admin.html')
    elif not request.session.get('is_admin', False) and request.session.get('is_user', False):
        return redirect('pagesForUser:Home_user')
    else:
        return redirect('pages:Home')
    
# Done
def Add_book(request):
    if request.session.get('is_admin', False) and not request.session.get('is_user', False):
        title = request.POST.get('title')
        bookId = request.POST.get('id')
        author = request.POST.get('author')
        category = request.POST.get('category')
        briefDescription = request.POST.get('briefDescription')
        description = request.POST.get('description')
        # Use request.FILES when you upload file like image
        image = request.FILES.get('addImage')
        if Book.objects.filter(bookId=bookId).exists():
            return JsonResponse({'message': 'The ID is already taken, check it and try again'}, status=226)
        
        account = Account_admin.objects.get(username=request.session.get('username'))
        data = Book(title=title, bookId=bookId, author=author, category=category, briefDescription=briefDescription, 
                    description=description, image=image, available=True, owner=account)
        if request.method == "POST":
            data.save()
        return render(request, 'pagesForAdmin\Add_book.html')
    elif not request.session.get('is_admin', False) and request.session.get('is_user', False):
        return redirect('pagesForUser:Home_user')
    else:
        return redirect('pages:Home')

# Done
def Edit_book(request, bookId):
    if request.session.get('is_admin', False) and not request.session.get('is_user', False):
        if request.method == 'POST':
            book = Book.objects.get(bookId=bookId)
            title = request.POST.get('title')
            newBookId = request.POST.get('id')
            author = request.POST.get('author')
            category = request.POST.get('category')
            briefDescription = request.POST.get('briefDescription')
            description = request.POST.get('description')
            image = request.FILES.get('addImage')

            if bookId != newBookId:
                if Book.objects.filter(bookId=newBookId).exists():
                    return JsonResponse({'message': 'The ID is already taken, check it and try again'}, status=226)
                else :
                    account = Account_admin.objects.get(username=request.session.get('username'))
                    data = Book(title=title, bookId=newBookId, author=author, category=category, briefDescription=briefDescription, 
                                description=description, image=image, available=True, owner=account)
                    # print(bookId)
                    # print(newBookId)
                    # print(book.bookId)
                    book.delete()
                    data.save()
                    return redirect('pagesForAdmin:Edit_book', bookId=newBookId)
                    # return HttpResponse("Book edited successfully.")
            else:
                book.title = title
                book.author = author
                book.category = category
                book.briefDescription = briefDescription
                book.description = description
                book.image = image
                book.save()
                return HttpResponse("Book edited successfully.")
        else:
            book = get_object_or_404(Book, bookId=bookId)
            return render(request, 'pagesForAdmin\Edit_on_book.html', {'book': book})
    
    elif not request.session.get('is_admin', False) and request.session.get('is_user', False):
        return redirect('pagesForUser:Home_user')
    else:
        return redirect('pages:Home')
    
# Done
def Admin_view_available_books(request):
    if request.session.get('is_admin', False) and not request.session.get('is_user', False):
        account = Account_admin.objects.get(username=request.session.get('username'))
        books = Book.objects.all().filter(owner=account, available=True)
        return render(request, 'pagesForAdmin\Admin_view_available_books.html', {'books': books})
    elif not request.session.get('is_admin', False) and request.session.get('is_user', False):
        return redirect('pagesForUser:Home_user')
    else:
        return redirect('pages:Home')
      
# Done
def Admin_view_all_books(request):
    if request.session.get('is_admin', False) and not request.session.get('is_user', False):
        account = Account_admin.objects.get(username=request.session.get('username'))
        books = Book.objects.all().filter(owner=account)
        return render(request, 'pagesForAdmin\Admin_view_all_books.html', {'books': books})
    elif not request.session.get('is_admin', False) and request.session.get('is_user', False):
        return redirect('pagesForUser:Home_user')
    else:
        return redirect('pages:Home')
    
# Done
def Admin_display_book(request, bookId):
    if request.session.get('is_admin', False) and not request.session.get('is_user', False):
        book = get_object_or_404(Book, bookId=bookId)
        return render(request, 'pagesForAdmin\Admin_display_book.html', {'book': book})
    elif not request.session.get('is_admin', False) and request.session.get('is_user', False):
        return redirect('pagesForUser:Home_user')
    else:
        return redirect('pages:Home')
    
# Done
def Admin_delete_book(request, bookId):
    if request.session.get('is_admin', False) and not request.session.get('is_user', False):
        if request.method == 'POST':
            try:
                book = Book.objects.get(bookId=bookId)
                book.delete()
                return JsonResponse({'message': 'Book deleted successfully'})
            except Book.DoesNotExist:
                return JsonResponse({'error': 'Book not found'}, status=404)
        return redirect('Home_admin')
    elif not request.session.get('is_admin', False) and request.session.get('is_user', False):
        return redirect('pagesForUser:Home_user')
    else:
        return redirect('pages:Home')

OnlineLibrary/templates/pagesForAdmin/Add_book.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title>Add Book</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}">
    <link rel="stylesheet" href="{% static 'Css Files/FormPages.css' %}">
  </head>
  <body>
    <nav class="AdminNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
          <li><a href="{% url 'pagesForAdmin:Home_admin' %}">Home</a></li>
          <li><a href="{% url 'pagesForAdmin:Add_book' %}">Add new book</a></li>
          <li><a href="{% url 'pagesForAdmin:Admin_view_all_books' %}">All books</a></li>
          <li><a href="{% url 'pagesForAdmin:Admin_view_available_books' %}">Available books</a></li>
          <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
      </ul>
    </nav>
    <div class="PageContent">
      <h1>Add book</h1>
      <p class="Note">Please fill out the information of the book you want to add.</h3>
      <form method="post" name="addBookForm" id="addBookForm">
        {% csrf_token %}
        
        <label for="title">Book Title</label>
        <input
          type="text"
          id="title"
          name="title"
          autofocus
          placeholder="Book title"
          title="Enter the book title"
        />
        <div id="titleValidationMessage">
          <ul id="titleError"></ul>
        </div>
        <label for="bookID">ID of the book</label>
        <input
          type="number"
          id="bookID"
          name="bookID"
          placeholder="ID"
          title="Enter the ID (should be numbers)"
        />
        <div id="idValidationMessage">
          <ul id="idError"></ul>
        </div>
        <label for="author">Author</label>
        <input
          type="text"
          id="author"
          name="author"
          placeholder="Author"
          title="Enter the author of the book"
        />
        <div id="authorValidationMessage">
          <ul id="authorError"></ul>
        </div>
        <label for="Category">Category</label>
        <input
          type="text"
          id="Category"
          name="Category"
          placeholder="Category"
          title="Enter the Category of the book"
        />
        <div id="categoryValidationMessage">
          <ul id="categoryError"></ul>
        </div>
        <label for="textarea1">Brief description</label>
        <textarea
          id="briefDescription"
          name="briefDescription"
          title="Write a brief description of the book"
          placeholder="Brief description"
          cols="30"
          rows="5"
        ></textarea>
        <div id="briefDescriptionValidationMessage">
          <ul id="briefDescriptionError"></ul>
        </div>
        <label for="textarea2">Description</label>
        <textarea
          id="description"
          name="description"
          title="Write a description of the book"
          placeholder="Description"
          cols="30"
          rows="10"
        ></textarea>
        <div id="descriptionValidationMessage">
          <ul id="descriptionError"></ul>
        </div>
        <input type="file" id="addImage" name="addImage"/>
        <label for="addImage">Choose Image</label>
        {% comment %} <img src="{% static 'Images/accept.png' %}" id="accept"> {% endcomment %}
        <div id="addImageValidationMessage">
          <ul id="addImageError"></ul>
        </div>
        <br>
        <div id="AddBookDiv">
          <p id="AddSuccessful">The book has been added successfully</p>
          <p id="Existing">The ID is already taken, check it and try again</p>
          <br>
          <br>
        </div>
        <input type="reset" id="ResetButton" title="To clear all data" />
        <button
          type="submit"
          id="addBookButton"
          name="addBookButton"
          value="Add book"
          title="To add book to the Library"
          onclick="validateAddBookForm()"
        >Add book
        </button>
      </form>
    </div>
    <script src="{% static 'Java Script Files/Validation.js' %}"></script>
  </body>
</html>

OnlineLibrary/templates/pagesForAdmin/Admin_display_book.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>available books</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{% static 'Css Files/BookPages.css' %}" />
  </head>

  <body>
    <nav class="AdminNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
        <li><a href="{% url 'pagesForAdmin:Home_admin' %}">Home</a></li>
        <li><a href="{% url 'pagesForAdmin:Add_book' %}">Add new book</a></li>
        <li><a href="{% url 'pagesForAdmin:Admin_view_all_books' %}">All books</a></li>
        <li><a href="{% url 'pagesForAdmin:Admin_view_available_books' %}">Available books</a></li>
        <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
      </ul>
    </nav>

    <div id="the available books" class="PageContent">
        <br /><br />
        <h1>Book Details</h1>
        
        <div class="book_rectangle">
        <img
            src="{{book.image.url}}"
            alt="book cover"
            width="240"
            height="360"
        />
        <div class="book_rectangle_header">
            <h3>{{book.title}}</h3>
        </div>
        <div class="book_rectangle_body">
            <ul>
            <li><strong>Status: </strong>{% if book.available == True %}Available{% elif book.available == False %}Not Available{% endif %}</li>
            <br>
            <li><strong>Id: </strong>{{book.bookId}}</li>
            <br>
            <li><strong>Author: </strong>{{book.author}}</li>
            <br>
            <li><strong>Category: </strong>{{book.category}}</li>
            <br>
            <li>
                <strong>Brief Description: </strong>{{book.briefDescription}}</li>
            <br>
            <li>
                <strong>Description: </strong>{{book.description}}</li>
            </ul>
        </div>
        {% if book.available == True %}
            <a href="{% url 'pagesForAdmin:Edit_book' book.bookId %}"><button><span></span>Edit</button></a>
            <button onclick="deleteBook('{{book.bookId}}')"><span></span>Delete</button>
        {% endif %}
        </div>

    </div>
    
    <script>const csrfToken = "{{ csrf_token }}";</script>
    <script src="{% static 'Java Script Files/delete.js' %}"></script>
  </body>
</html>

OnlineLibrary/templates/pagesForAdmin/Admin_view_all_books.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>All books</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{% static 'Css Files/BookPages.css' %}" />
  </head>

  <body>
    <nav class="AdminNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
        <li><a href="{% url 'pagesForAdmin:Home_admin' %}">Home</a></li>
        <li><a href="{% url 'pagesForAdmin:Add_book' %}">Add new book</a></li>
        <li><a href="{% url 'pagesForAdmin:Admin_view_all_books' %}">All books</a></li>
        <li><a href="{% url 'pagesForAdmin:Admin_view_available_books' %}">Available books</a></li>
        <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
      </ul>
    </nav>

    <div id="the books" class="PageContent">
        <br /><br />
        <h1>My All Books</h1>
        
        {% for book in books %}
          <div id="{{ book.bookId }}" class="book_rectangle">
            <img
              src="{{book.image.url}}"
              alt="book cover"
              width="200"
              height="300"
            />
            <div class="book_rectangle_header">
              <h3><a href="{% url 'pagesForAdmin:Admin_display_book' book.bookId %}" class="Details">{{ book.title }}</a></h3>
            </div>
            <div class="book_rectangle_body">
              <ul>
                <li><strong>Status: </strong>{% if book.available == True %}Available{% elif book.available == False %}Not Available{% endif %}</li>
                <br>
                <li><strong>Id: </strong>{{book.bookId}}</li>
                <br>
                <li><strong>Author: </strong>{{book.author}}</li>
                <br>
                <li><strong>Category: </strong>{{book.category}}</li>
                <br>
                <li>
                  <strong>Brief Description: </strong>{{book.briefDescription}}</li>
                <br>
                <li>
                  <strong>Description: </strong>{{book.description}}</li>
              </ul>
            </div>
            {% if book.available == True %}
              <a href="{% url 'pagesForAdmin:Edit_book' book.bookId %}"><button><span></span>Edit</button></a>
              <button onclick="deleteBook('{{book.bookId}}')"><span></span>Delete</button>
            {% endif %}
          </div>
        {% empty %}
            <p>There is no books at the moment.</p>
        {% endfor %}

    </div>

    <script>const csrfToken = "{{ csrf_token }}";</script>
    <script src="{% static 'Java Script Files/delete.js' %}"></script>
  </body>
</html>

OnlineLibrary/templates/pagesForAdmin/Admin_view_available_books.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>available books</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{% static 'Css Files/BookPages.css' %}" />
  </head>

  <body>
    <nav class="AdminNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
        <li><a href="{% url 'pagesForAdmin:Home_admin' %}">Home</a></li>
        <li><a href="{% url 'pagesForAdmin:Add_book' %}">Add new book</a></li>
        <li><a href="{% url 'pagesForAdmin:Admin_view_all_books' %}">All books</a></li>
        <li><a href="{% url 'pagesForAdmin:Admin_view_available_books' %}">Available books</a></li>
        <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
      </ul>
    </nav>

    <div id="the books" class="PageContent">
        <br /><br />
        <h1>My Available Books</h1>
        
        {% for book in books %}
          {% if book.available == True %}
            <div id="{{ book.bookId }}" class="book_rectangle">
              <img
                src="{{book.image.url}}"
                alt="book cover"
                width="200"
                height="300"
              />
              <div class="book_rectangle_header">
                <h3><a href="{% url 'pagesForAdmin:Admin_display_book' book.bookId %}" class="Details">{{ book.title }}</a></h3>
              </div>
              <div class="book_rectangle_body">
                <ul>
                  <li><strong>Status: </strong>{% if book.available == True %}Available{% elif book.available == False %}Not Available{% endif %}</li>
                  <br>
                  <li><strong>Id: </strong>{{book.bookId}}</li>
                  <br>
                  <li><strong>Author: </strong>{{book.author}}</li>
                  <br>
                  <li><strong>Category: </strong>{{book.category}}</li>
                  <br>
                  <li>
                    <strong>Brief Description: </strong>{{book.briefDescription}}</li>
                  <br>
                  <li>
                    <strong>Description: </strong>{{book.description}}</li>
                </ul>
              </div>
              {% if book.available == True %}
                <a href="{% url 'pagesForAdmin:Edit_book' book.bookId %}"><button><span></span>Edit</button></a>
                <button onclick="deleteBook('{{book.bookId}}')"><span></span>Delete</button>
              {% endif %}
            </div>
          {% endif %}
        {% empty %}
            <p>There is no available books at the moment.</p>
        {% endfor %}

    </div>

    <script>const csrfToken = "{{ csrf_token }}";</script>
    <script src="{% static 'Java Script Files/delete.js' %}"></script>
  </body>
</html>

OnlineLibrary/templates/pagesForAdmin/Edit_on_book.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title>Edit Book</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}">
    <link rel="stylesheet" href="{% static 'Css Files/FormPages.css' %}">
  </head>
  <body>
    <nav class="AdminNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
          <li><a href="{% url 'pagesForAdmin:Home_admin' %}">Home</a></li>
          <li><a href="{% url 'pagesForAdmin:Add_book' %}">Add new book</a></li>
          <li><a href="{% url 'pagesForAdmin:Admin_view_all_books' %}">All books</a></li>
          <li><a href="{% url 'pagesForAdmin:Admin_view_available_books' %}">Available books</a></li>
          <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
      </ul>
    </nav>
    <div class="PageContent">
      <h1>Edit on a book</h1>
      <p class="Note">Please modify the information of the book that is incorrect</h3>
      <form method="post" name="editBookForm" id="editBookForm">
        {% csrf_token %}
        
        <label for="title">Book Title</label>
        <input
          type="text"
          id="title"
          name="title"
          autofocus
          placeholder="Book title"
          title="Enter the book title"
          value="{{ book.title }}"
        />
        <div id="titleValidationMessage">
          <ul id="titleError"></ul>
        </div>
        <label for="bookID">ID of the book</label>
        <input
          type="number"
          id="bookID"
          name="bookID"
          placeholder="ID"
          title="Enter the ID (should be numbers)"
          value="{{ book.bookId }}"
          {% comment %} disabled {% endcomment %}
        />
        <div id="idValidationMessage">
          <ul id="idError"></ul>
        </div>
        <label for="author">Author</label>
        <input
          type="text"
          id="author"
          name="author"
          placeholder="Author"
          title="Enter the author of the book"
          value="{{ book.author }}"
        />
        <div id="authorValidationMessage">
          <ul id="authorError"></ul>
        </div>
        <label for="Category">Category</label>
        <input
          type="text"
          id="Category"
          name="Category"
          placeholder="Category"
          title="Enter the Category of the book"
          value="{{ book.category }}"
        />
        <div id="categoryValidationMessage">
          <ul id="categoryError"></ul>
        </div>
        <label for="textarea1">Brief description</label>
        <textarea
          id="briefDescription"
          name="briefDescription"
          title="Write a brief description of the book"
          placeholder="Brief description"
          cols="30"
          rows="5"
        >{{ book.briefDescription }}</textarea>
        <div id="briefDescriptionValidationMessage">
          <ul id="briefDescriptionError"></ul>
        </div>
        <label for="textarea2">Description</label>
        <textarea
          id="description"
          name="description"
          title="Write a description of the book"
          placeholder="Description"
          cols="30"
          rows="10"
        >{{ book.description }}</textarea>
        <div id="descriptionValidationMessage">
          <ul id="descriptionError"></ul>
        </div>
        <input type="file" id="addImage" name="addImage"/>
        <label for="addImage">Choose Image</label>
        {% comment %} <img src="{% static 'Images/accept.png' %}" id="accept"> {% endcomment %}
        <div id="addImageValidationMessage">
          <ul id="addImageError"></ul>
        </div>
        <br>
        <div id="EditBookDiv">
          <p id="EditSuccessful">The book has been edited successfully</p>
          <p id="Existing">The ID is already taken, check it and try again</p>
          <br>
          <br>
        </div>
        <input type="reset" id="ResetButton" title="To clear all data" />
        <button
          type="submit"
          id="addBookButton"
          name="addBookButton"
          value="Add book"
          title="To add book to the Library"
          onclick="validateEditBookForm('{{book.bookId}}')"
        >Edit book
        </button>
      </form>
    </div>
    <script src="{% static 'Java Script Files/Validation.js' %}"></script>
  </body>
</html>

OnlineLibrary/templates/pagesForAdmin/Home_admin.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{% static 'Css Files/BookPages.css' %}" />
  </head>
  <body>
    <nav class="AdminNav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
          <li><a href="{% url 'pagesForAdmin:Home_admin' %}">Home</a></li>
          <li><a href="{% url 'pagesForAdmin:Add_book' %}">Add new book</a></li>
          <li><a href="{% url 'pagesForAdmin:Admin_view_all_books' %}">All books</a></li>
          <li><a href="{% url 'pagesForAdmin:Admin_view_available_books' %}">Available books</a></li>
          <li><a href="{% url 'pages:Log_out' %}">Log out</a></li>
      </ul>
    </nav>
    <div class="Home">
      <h1><b>Welcome To Library Website</b></h1>
      <p>
        This site serves as a library where you can add new books or borrow them
      </p>
    </div>
  </body>
</html>