OnlineLibrary/OnlineLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('Admin_Pages/', include('pagesForAdmin.urls')),
    path('User_Pages/', include('pagesForUser.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# انا اللي كاتب اللي تحت 
# static : conf urls static
# setting : conf

OnlineLibrary/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.Home, name='Home'),
    path('Sign_up', views.Sign_up, name='Sign_up'),
    path('Login', views.Login, name='Login'),
    path('Log_out', views.Log_out, name='Log_out'),
]

OnlineLibrary/templates/pages/Home.html
<!-- name= {{name}} -->
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
  </head>
  <body>
    <nav class="Nav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
          <li><a href="{% url 'pages:Home' %}">Home</a></li>
          <li><a href="{% url 'pages:Sign_up' %}">Sign Up </a></li>
          <li><a href="{% url 'pages:Login' %}">Login</a></li>
      </ul>
    </nav>
    <div class="Home">
      <h1>welcom to library</h1>
      <p>
          Reading gives us another place to go when we are forced to stay in our places,
            and a book is not only a friend, but it makes you friends.
      </p>
      <div>
          <a href="{% url 'pages:Sign_up' %}">
            <button type="button" class="home">
                <span></span>SIGN UP
            </button>
          </a>
          <a href="{% url 'pages:Login' %}">
            <button type="button" class="home">
                <span></span>LOGIN
            </button>
          </a>
      </div> 
    </div>
  </body>
</html>

OnlineLibrary/templates/pages/Login.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{%static 'Css Files/FormPages.css' %}" />
  </head>
  <body>
    <nav class="Nav">
      <img src="{% static 'Images/logo0.png' %}" class="logo">
      <ul>
        <li><a href="{% url 'pages:Home' %}">Home</a></li>
        <li><a href="{% url 'pages:Sign_up' %}">Sign Up </a></li>
        <li><a href="{% url 'pages:Login' %}">Login</a></li>
      </ul>
    </nav>
    <div class="PageContent">
      <h1>Login</h1>
      <form method="post" class="loginForm" name="loginForm" id="loginForm">
        {% csrf_token %}
        <div id="LoginDiv">
          <p id="invalidUsername">Invalid Username or password</p>
          <br>
          <br>
        </div>
          <div>
            <label>Username</label>
            <input type="text" name="username" placeholder="Please enter username" title="Enter the Username">
            <div id="usernameValidationMessage">
              <ul id="usernameError"></ul>
            </div>
          </div>
          <div>
            <label>Password</label>
              <input type="password" name="password" placeholder="Please enter password" title="Enter the password">
              <div id="passwordValidationMessage">
                <ul id="passwordError"></ul>
              </div>
          </div>
          <div>
            <input type="submit" id="Login" value="Login" onclick="validateLoginForm()">
          </div>
      </form>
    </div>
    <script src="{% static 'Java Script Files/Validation.js' %}"></script>
  </body>
</html>

OnlineLibrary/templates/pages/Sign_up.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title>Sign up</title>
    <link rel="stylesheet" href="{% static 'Css Files/Nav.css' %}" />
    <link rel="stylesheet" href="{%static 'Css Files/FormPages.css' %}" />
  </head>
  <body>

    <nav class="Nav">
        <img src="{% static 'Images/logo0.png' %}" class="logo">
        <ul>
          <li><a href="{% url 'pages:Home' %}">Home</a></li>
          <li><a href="{% url 'pages:Sign_up' %}">Sign Up </a></li>
          <li><a href="{% url 'pages:Login' %}">Login</a></li>
        </ul>
    </nav>

    <div class="PageContent">
      <h1>Sign up</h1>
      <form method="Post" name="signupForm" id="signupForm">
        {% csrf_token %}
        <div id="SignUpDiv">
          <p id="SignUpSuccessful">Your Account has been Successfully created</p>
          <p id="Existing">The Username is already taken try another one</p>
          <br>
          <br>
        </div>
        <div>
            <label>Username</label>
            <input type="text" name="username" placeholder="Please enter username">
            <div id="usernameValidationMessage">
              <ul id="usernameError"></ul>
            </div>
        </div>
        <div>
            <label>Password</label>
            <input type="password" name="password" id="password" placeholder="Please enter password" title="Password must be at least 8 characters long, contain both numbers and letters, and have numbers and letters continuously.">
            <div id="passwordValidationMessage">
              <ul id="passwordError"></ul>
            </div>
        </div>
        <div>
            <label>Repeat Password</label>
            <input type="password" id="repeatPassword" name="repeatPassword" placeholder="Please enter repeat password">
            <div id="repeatPasswordValidationMessage">
              <ul id="repeatPasswordError"></ul>
            </div>
        </div>
        <div>
            <label>ID</label>
            <input type="number" name="id" placeholder="Please enter ID">
            <div id="idUserValidationMessage">
              <ul id="idUserError"></ul>
            </div>
        </div>
        <div>
          <label>email</label>
          <input type="email" name="email" placeholder="Please enter email" title="Enter Your email">
          <div id="emailValidationMessage">
            <ul id="emailError"></ul>
          </div>
        </div>
        <label>Choose type of action</label>
        <select name="typeOfAction" id="typeOfAction">
            <option value="user">User</option>
            <option value="admin">Admin</option>
        </select>
        <input type="submit" value="Sign up" onclick="validateSignupForm()">
      </form>
    </div>
    <script src="{% static 'Java Script Files/Validation.js' %}"></script>
  </body>
</html>